package com.n37.foodordering.model;

import java.util.Date;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.food_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer foodId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.user_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Date createdDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.food_id
     *
     * @return the value of comment.food_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.food_id
     *
     * @param foodId the value for comment.food_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.user_id
     *
     * @return the value of comment.user_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.user_id
     *
     * @param userId the value for comment.user_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.created_date
     *
     * @return the value of comment.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.created_date
     *
     * @param createdDate the value for comment.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }
}