package com.n37.foodordering.model;

import java.util.Date;

public class Food_order_detail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order_detail.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order_detail.total_price
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Long totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order_detail.ship_price
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Long shipPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order_detail.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order_detail.order_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order_detail.food_quantity
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer foodQuantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order_detail.id
     *
     * @return the value of food_order_detail.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order_detail.id
     *
     * @param id the value for food_order_detail.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order_detail.total_price
     *
     * @return the value of food_order_detail.total_price
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Long getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order_detail.total_price
     *
     * @param totalPrice the value for food_order_detail.total_price
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setTotalPrice(Long totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order_detail.ship_price
     *
     * @return the value of food_order_detail.ship_price
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Long getShipPrice() {
        return shipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order_detail.ship_price
     *
     * @param shipPrice the value for food_order_detail.ship_price
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setShipPrice(Long shipPrice) {
        this.shipPrice = shipPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order_detail.created_date
     *
     * @return the value of food_order_detail.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order_detail.created_date
     *
     * @param createdDate the value for food_order_detail.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order_detail.order_id
     *
     * @return the value of food_order_detail.order_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order_detail.order_id
     *
     * @param orderId the value for food_order_detail.order_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order_detail.food_quantity
     *
     * @return the value of food_order_detail.food_quantity
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getFoodQuantity() {
        return foodQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order_detail.food_quantity
     *
     * @param foodQuantity the value for food_order_detail.food_quantity
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setFoodQuantity(Integer foodQuantity) {
        this.foodQuantity = foodQuantity;
    }
}