package com.n37.foodordering.model;

import java.util.Date;

public class Food {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.upload_time
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.decription
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String decription;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.image
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.unit_price
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Long unitPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.status
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.category
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.restaurant_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer restaurantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.id
     *
     * @return the value of food.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.id
     *
     * @param id the value for food.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.name
     *
     * @return the value of food.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.name
     *
     * @param name the value for food.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.upload_time
     *
     * @return the value of food.upload_time
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.upload_time
     *
     * @param uploadTime the value for food.upload_time
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.decription
     *
     * @return the value of food.decription
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getDecription() {
        return decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.decription
     *
     * @param decription the value for food.decription
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setDecription(String decription) {
        this.decription = decription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.image
     *
     * @return the value of food.image
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.image
     *
     * @param image the value for food.image
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.unit_price
     *
     * @return the value of food.unit_price
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Long getUnitPrice() {
        return unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.unit_price
     *
     * @param unitPrice the value for food.unit_price
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setUnitPrice(Long unitPrice) {
        this.unitPrice = unitPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.status
     *
     * @return the value of food.status
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.status
     *
     * @param status the value for food.status
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.category
     *
     * @return the value of food.category
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.category
     *
     * @param category the value for food.category
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.restaurant_id
     *
     * @return the value of food.restaurant_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.restaurant_id
     *
     * @param restaurantId the value for food.restaurant_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }
}