package com.n37.foodordering.model;

import java.util.Date;

public class Food_order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.amount
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.payment
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private String payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.customer_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer customerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.redtaurant_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Integer redtaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food_order.is_delete
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    private Boolean isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.id
     *
     * @return the value of food_order.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.id
     *
     * @param id the value for food_order.id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.amount
     *
     * @return the value of food_order.amount
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.amount
     *
     * @param amount the value for food_order.amount
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.created_date
     *
     * @return the value of food_order.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.created_date
     *
     * @param createdDate the value for food_order.created_date
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.payment
     *
     * @return the value of food_order.payment
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public String getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.payment
     *
     * @param payment the value for food_order.payment
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setPayment(String payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.customer_id
     *
     * @return the value of food_order.customer_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.customer_id
     *
     * @param customerId the value for food_order.customer_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.redtaurant_id
     *
     * @return the value of food_order.redtaurant_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Integer getRedtaurantId() {
        return redtaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.redtaurant_id
     *
     * @param redtaurantId the value for food_order.redtaurant_id
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setRedtaurantId(Integer redtaurantId) {
        this.redtaurantId = redtaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food_order.is_delete
     *
     * @return the value of food_order.is_delete
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public Boolean getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food_order.is_delete
     *
     * @param isDelete the value for food_order.is_delete
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }
}