package com.n37.foodordering.model;

public class Menu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.restaurant_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer restaurantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.food_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer foodId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.restaurant_id
     *
     * @return the value of menu.restaurant_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getRestaurantId() {
        return restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.restaurant_id
     *
     * @param restaurantId the value for menu.restaurant_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setRestaurantId(Integer restaurantId) {
        this.restaurantId = restaurantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.food_id
     *
     * @return the value of menu.food_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.food_id
     *
     * @param foodId the value for menu.food_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setFoodId(Integer foodId) {
        this.foodId = foodId;
    }
}