package com.n37.foodordering.model;

import java.util.Date;

public class Restaurant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.user_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.created_date
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.description
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column restaurant.image
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.id
     *
     * @return the value of restaurant.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.id
     *
     * @param id the value for restaurant.id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.name
     *
     * @return the value of restaurant.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.name
     *
     * @param name the value for restaurant.name
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.user_id
     *
     * @return the value of restaurant.user_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.user_id
     *
     * @param userId the value for restaurant.user_id
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.created_date
     *
     * @return the value of restaurant.created_date
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.created_date
     *
     * @param createdDate the value for restaurant.created_date
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.description
     *
     * @return the value of restaurant.description
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.description
     *
     * @param description the value for restaurant.description
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column restaurant.image
     *
     * @return the value of restaurant.image
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column restaurant.image
     *
     * @param image the value for restaurant.image
     *
     * @mbg.generated Thu Sep 01 09:03:08 ICT 2022
     */
    public void setImage(String image) {
        this.image = image;
    }
}