package com.n37.foodordering.mapper;

import com.n37.foodordering.model.Food_order_detail;
import com.n37.foodordering.model.Food_order_detailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Food_order_detailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    long countByExample(Food_order_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int deleteByExample(Food_order_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int insert(Food_order_detail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int insertSelective(Food_order_detail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    List<Food_order_detail> selectByExample(Food_order_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    Food_order_detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Food_order_detail row, @Param("example") Food_order_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByExample(@Param("row") Food_order_detail row, @Param("example") Food_order_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByPrimaryKeySelective(Food_order_detail row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table food_order_detail
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByPrimaryKey(Food_order_detail row);
}