package com.n37.foodordering.mapper;

import com.n37.foodordering.model.Restaurant;
import com.n37.foodordering.model.RestaurantExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RestaurantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    long countByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int deleteByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int insert(Restaurant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int insertSelective(Restaurant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    List<Restaurant> selectByExample(RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    Restaurant selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByExampleSelective(@Param("row") Restaurant row, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByExample(@Param("row") Restaurant row, @Param("example") RestaurantExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByPrimaryKeySelective(Restaurant row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table restaurant
     *
     * @mbg.generated Tue Aug 30 17:16:15 ICT 2022
     */
    int updateByPrimaryKey(Restaurant row);
}